Vagrant.configure("2") do |config|
  config.vm.box = "generic/rocky9"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip:"192.168.1.2"
  config.vm.synced_folder "./", "/home/vagrant/ansible_lab"
end